###
#   Database Settings
###
spring:
  application:
    name: book-service-app
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

###
#   H2 Settings
###
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
 
###
#   Server settings
###
server:
  port: 9000


#management endpoints on a separate port
management:
  server:
    port: 9001
    address: 127.0.0.1
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: apisdatacustom,health    
  endpoint:
    health:
      enabled: true
      show-details: always