DROP TABLE IF EXISTS TBL_BOOK;
CREATE TABLE TBL_BOOK(ID BIGINT PRIMARY KEY, NAME VARCHAR(255), PRICE FLOAT);

DROP TABLE IF EXISTS API_HEALTH_CHECK_MEASURE;
CREATE TABLE API_HEALTH_CHECK_MEASURE(ID BIGINT PRIMARY KEY, MEASURE_NAME VARCHAR(255), MEASURE_NUMBER_VALUE FLOAT, API_NAME VARCHAR(255), MEASURE_STRING_VALUE VARCHAR(255), MEASURE_STARTED_DATE TIMESTAMP);